# Generated by Django 4.0.3 on 2022-04-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activities_id', models.CharField(db_column='Activities_id', max_length=45, primary_key=True, serialize=False)),
                ('activity_desc', models.CharField(blank=True, db_column='Activity_desc', max_length=1000, null=True)),
                ('activity_timelength', models.IntegerField(blank=True, db_column='Activity_timeLength', null=True)),
                ('activity_photo', models.ImageField(blank=True, default='activity.jpg', upload_to='photos_activities')),
                ('activity_participant', models.IntegerField(blank=True, default=1)),
                ('activity_place', models.CharField(blank=True, default='Home', max_length=25)),
                ('activity_tag', models.CharField(blank=True, default='Game', max_length=20)),
            ],
            options={
                'db_table': 'activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserHash',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=45, primary_key=True, serialize=False)),
                ('hashnum', models.CharField(db_column='Password', default='', max_length=1000)),
            ],
            options={
                'db_table': 'user_hash',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(db_column='User_ID', max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=45)),
                ('user_name', models.CharField(blank=True, db_column='User_Name', default='null', max_length=20, null=True)),
                ('user_photo', models.ImageField(blank=True, default='photos_user/Nick_Wilde.jpg', upload_to='photos_user/')),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.IntegerField(db_column='Note_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_column='Created_At', null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_info_user', models.ForeignKey(db_column='User_info_User_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='Funbox.userinfo')),
            ],
            options={
                'db_table': 'note',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(default='Hiking', on_delete=django.db.models.deletion.CASCADE, to='Funbox.activities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Funbox.userinfo')),
            ],
            options={
                'db_table': 'user_preference',
                'managed': True,
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
