# Generated by Django 4.0.3 on 2022-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_photo',
            field=models.ImageField(blank=True, default='activity.jpg', upload_to='media/photos_activities'),
        ),
    ]
