# Generated by Django 4.0.3 on 2022-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(blank=True, db_column='User_Name', default='null', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_photo',
            field=models.ImageField(blank=True, default='photos_user/Nick_Wilde.jpg', upload_to='photos_user/'),
        ),
    ]
