# Generated by Django 4.0.3 on 2022-04-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0002_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
