# Generated by Django 4.0.3 on 2022-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0002_alter_activities_activity_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AlterField(
            model_name='activities',
            name='activities_id',
            field=models.CharField(db_column='Activities_id', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_desc',
            field=models.CharField(blank=True, db_column='Activity_desc', max_length=1000, null=True),
        ),
    ]
