# Generated by Django 4.0.3 on 2022-04-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0002_activity_alter_activities_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_photo',
        ),
    ]
