# Generated by Django 4.0.3 on 2022-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0003_delete_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notes',
            name='activity_photo',
            field=models.ImageField(blank=True, default='notes.jpg', upload_to='photos_notes'),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
