# Generated by Django 4.0.3 on 2022-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0003_delete_activity_alter_activities_activities_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_photo',
            field=models.ImageField(blank=True, default='activity.jpg', upload_to='photos_activities'),
        ),
    ]
