# Generated by Django 4.0.3 on 2022-04-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Funbox', '0004_alter_notes_unique_together_notes_activity_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notelikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Funbox.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Funbox.userinfo')),
            ],
            options={
                'managed': True,
                'unique_together': {('user', 'note')},
            },
        ),
    ]
